[tool.poetry]
name = "kungfu"
version = "2.4.0"
description = ""
authors = ["Keren DONG <keren.dong@kungfu.link>"]

[tool.poetry.dependencies]
python = ">=3.7.1, <4.0"
# Control
click = "^8.0.1"
psutil = "^5.8.0"
wcwidth = "^0.2.5"
tabulate = "^0.8.9"
PyYAML = "^5.4.1"
# Data Structures
sortedcontainers = "^2.4.0"
recordclass = "^0.14.3"
dotted-dict = "^1.1.3"
# Numeric
numpy = "^1.21.1"
pandas = "^1.2.0"
statsmodels = "^0.12.2"
plotly = "^5.1.0"
# Legacy
chinesecalendar = "^1.5.1"

[tool.poetry.dev-dependencies]
black = "^21.7b0"
conan = "^1.38.0"
Nuitka = "^0.6.16"
pyinstaller = "^4.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
