[tool.poetry]
name = "kungfu"
version = "0.0.0"
description = "Kungfu Core Library"
license = "Apache-2.0"
authors = ["Kungfu Trader <info@kungfu.link>"]
homepage = "https://www.kungfu-trader.com"
repository = "https://github.com/kungfu-trader/kungfu.git"
packages = [
    { include = "kungfu", from = "src/python" },
]

[tool.poetry.dependencies]
python = "~3.9"

#### Compiler #############################################
black = "^22.1.0"
nuitka = ">=0.6.17 <0.6.18"
pdm = "^1.12.0"
poetry-core = "^1.0.0"
scons = "^4.3.0"

#### Console ##############################################
click = "^8.0.0"
psutil = "^5.8.0"
tabulate = "^0.8.9"

#### Numeric ##############################################
numpy = "^1.22.0"
pandas = "^1.4.0"
scipy = ">=1.7 <1.8"
statsmodels = "^0.12.2"
plotly = "^5.4.0"

#### Legacy ###############################################
chinesecalendar = "^1.6.0"

[tool.poetry.dev-dependencies]
conan = "^1.46.2"
pyinstaller = "^4.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
