[tool.poetry]
name = "kungfu"
version = "0.0.0"
description = "Kungfu Core Library"
license = "Apache-2.0"
authors = ["Kungfu Trader <info@kungfu.link>"]
homepage = "https://www.kungfu-trader.com"
repository = "https://github.com/kungfu-trader/kungfu.git"
packages = [
    { include = "kungfu", from = "src/python" },
]

[tool.poetry.dependencies]
python = ">=3.7.1, <3.11"

#### Compiler #############################################
black = "^21.7b0"
Nuitka = "^0.6.16"
pdm = "^1.7.0"
poetry-core = "^1.0.0"
scons = "^4.1.0"

#### Console ##############################################
click = "^8.0.1"
psutil = "^5.8.0"
tabulate = "^0.8.9"

#### Numeric ##############################################
numpy = "^1.21.1"
pandas = "^1.2.0"
statsmodels = "^0.12.2"
plotly = "^5.1.0"

#### Legacy ###############################################
chinesecalendar = "^1.5.1"

[tool.poetry.dev-dependencies]
conan = "^1.42.0"
pyinstaller = "^4.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
