name: Mac CI

on:
  push:
    branches:
      - release
      - 2.3
      - ci

jobs:
  build:
    runs-on: macos-latest
    env:
      USE_HARD_LINKS: false
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.4
        with:
          node-version: '10.15.0'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@kungfu-trader'

      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Build Kungfu
        run: |
          npm install -g electron-builder
          pip install pipenv==2020.11.15
          yarn env-pypi-python
          yarn install
          yarn build

      - name: Publish to AWS S3
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: cn-northwest-1
        run: |
          yarn workspace @kungfu-trader/kungfu-core run package
          yarn workspace @kungfu-trader/kungfu-core publish-binary

      - name: Publish to GitHub Packages
        run: yarn workspace @kungfu-trader/kungfu-core publish-package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact to GitHub
        uses: actions/upload-artifact@v2
        with:
          path: app/build/app/*.dmg
